# Generated by Django 4.2.3 on 2023-07-19 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRate', '0003_movie_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MovieRate.genre'),
        ),
    ]
