# Generated by Django 4.2.3 on 2023-07-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRate', '0004_genre_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagerating',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
