# Generated by Django 4.2.3 on 2023-07-22 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRate', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierating',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
